/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gudang;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author redmibook
 */
public class registrasi extends javax.swing.JFrame {
    private DefaultTableModel model = null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k=new koneksi();

    /**
     * Creates new form login
     */
    public registrasi() {
        initComponents();
        k.connect();
        refreshTable();       
    }
    
    class user {
        int id_user, level;
        String username, password;
        
        public user () {
        username = textusernameregis.getText();
        password = textpassregis.getText();
        level = Integer.parseInt(combolevel.getSelectedItem().toString());
        }
    }
    
    public void refreshTable() {
        model = new DefaultTableModel();
        model.addColumn("ID User");
        model.addColumn("Username");
        model.addColumn("Password");
        model.addColumn("Level");
        tabeluser.setModel(model);
        try {
            this.stat = k.getKoneksi().prepareStatement("select * from user");
            this.rs = this.stat.executeQuery();
            while (rs.next()) {
                Object[] data = {
                    rs.getString("id_user"),
                    rs.getString("username"),
                    rs.getString("password"),
                    rs.getString("level")
                };
                model.addRow(data);
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        textidregis.setText("");
        textusernameregis.setText("");
        textpassregis.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textusernameregis = new javax.swing.JTextField();
        textpassregis = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textidregis = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_simpanuser = new javax.swing.JButton();
        btn_gantiuser = new javax.swing.JButton();
        btn_hapususer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabeluser = new javax.swing.JTable();
        combolevel = new javax.swing.JComboBox<>();
        btn_databk = new javax.swing.JButton();
        btn_databm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        jLabel1.setText("REGISTRASI");

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        textusernameregis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textusernameregisActionPerformed(evt);
            }
        });

        jLabel4.setText("Level");

        textidregis.setEnabled(false);
        textidregis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textidregisActionPerformed(evt);
            }
        });

        jLabel5.setText("ID user");

        btn_simpanuser.setText("Simpan");
        btn_simpanuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanuserActionPerformed(evt);
            }
        });

        btn_gantiuser.setText("Ganti");
        btn_gantiuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gantiuserActionPerformed(evt);
            }
        });

        btn_hapususer.setText("Hapus");
        btn_hapususer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapususerActionPerformed(evt);
            }
        });

        tabeluser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeluser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeluserMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabeluser);

        combolevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        combolevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combolevelActionPerformed(evt);
            }
        });

        btn_databk.setText("< Input data keluar");
        btn_databk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_databkActionPerformed(evt);
            }
        });

        btn_databm.setText("input data masuk >");
        btn_databm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_databmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textidregis)
                            .addComponent(textusernameregis, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textpassregis, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(combolevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_simpanuser)
                        .addGap(117, 117, 117)
                        .addComponent(btn_gantiuser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_hapususer))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_databk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_databm)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textidregis, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(textusernameregis, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textpassregis, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(combolevel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_hapususer)
                    .addComponent(btn_gantiuser)
                    .addComponent(btn_simpanuser))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_databk)
                    .addComponent(btn_databm))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textusernameregisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textusernameregisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textusernameregisActionPerformed

    private void textidregisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textidregisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textidregisActionPerformed

    private void btn_simpanuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanuserActionPerformed
        // TODO add your handling code here:
        try{
            user u = new user();
            this.stat = k.getKoneksi().prepareStatement("insert into user values (?,?,?,?)");
            stat.setInt(1,0);
            stat.setString(2, u.username);
            stat.setString(3, u.password);
            stat.setInt(4, u.level);
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn_simpanuserActionPerformed

    private void combolevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combolevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combolevelActionPerformed

    private void tabeluserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeluserMouseClicked
        // TODO add your handling code here:
        textidregis.setText(model.getValueAt(tabeluser.getSelectedRow(),0).toString());
        textusernameregis.setText(model.getValueAt(tabeluser.getSelectedRow(), 1).toString());
        textpassregis.setText(model.getValueAt(tabeluser.getSelectedRow(),2).toString());
    }//GEN-LAST:event_tabeluserMouseClicked

    private void btn_gantiuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gantiuserActionPerformed
        // TODO add your handling code here:
        try {
            user u = new user();
            this.stat = k.getKoneksi().prepareStatement("update user set username=?,"
                        + "password=?,level=? where id_user=?");
            stat.setString(1, u.username);
            stat.setString(2, u.password);
            stat.setInt(3, u.level);
            stat.setString(4,textidregis.getText());
            stat.executeUpdate();
            refreshTable();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn_gantiuserActionPerformed

    private void btn_hapususerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapususerActionPerformed
        // TODO add your handling code here:
        try {
            user u = new user();
            this.stat = k.getKoneksi().prepareStatement("delete from user where id_user=?");
            stat.setString(1,textidregis.getText());
            stat.executeUpdate();
            refreshTable();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn_hapususerActionPerformed

    private void btn_databkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_databkActionPerformed
        // TODO add your handling code here:
        tambahdatabarangk reg=new tambahdatabarangk();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_databkActionPerformed

    private void btn_databmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_databmActionPerformed
        // TODO add your handling code here:
        tambahdatabarangm reg=new tambahdatabarangm();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_databmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_databk;
    private javax.swing.JButton btn_databm;
    private javax.swing.JButton btn_gantiuser;
    private javax.swing.JButton btn_hapususer;
    private javax.swing.JButton btn_simpanuser;
    private javax.swing.JComboBox<String> combolevel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabeluser;
    private javax.swing.JTextField textidregis;
    private javax.swing.JTextField textpassregis;
    private javax.swing.JTextField textusernameregis;
    // End of variables declaration//GEN-END:variables
}
