/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gudang;

import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author redmibook
 */
public class tambahdatabarangk extends javax.swing.JFrame {
    private DefaultTableModel model=null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k=new koneksi();

    /**
     * Creates new form
     */
    public tambahdatabarangk() {
        initComponents();
        k.connect();
        refreshTable();
    }
    
    class tambahbarangk extends tambahdatabarangk{
        int id_barang_keluar,jumlah,id_barang;
        String tanggal_keluar;
        
        public tambahbarangk() {
            this.id_barang= Integer.parseInt(idbarangbk.getText());           
            try {
                Date date = tanggalkeluar.getDate();
                DateFormat dateformat = new SimpleDateFormat("YYYY-MM-dd");
                this.tanggal_keluar = dateformat.format(date);
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            this.jumlah= Integer.parseInt(textJumlahbk.getText());
        }
    }
        
        public void refreshTable() {
            model = new DefaultTableModel();
            model.addColumn("ID Barang Keluar");
            model.addColumn("ID Barang");
            model.addColumn("Jumlah");
            model.addColumn("Tanggal Keluar");
            tabelbk.setModel(model);
            try {
                this.stat = k.getKoneksi().prepareStatement("select * from barang_keluar ");
                this.rs = this.stat.executeQuery();
                while (rs.next()){
                    Object[] data = {
                        rs.getString("id_barang_keluar"),
                        rs.getString("id_barang"),
                        rs.getString("jumlah"),
                        rs.getString("tanggal_keluar")
                    };
                    model.addRow(data);
                }
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tombolSimpanbk = new javax.swing.JButton();
        tanggalkeluar = new com.toedter.calendar.JDateChooser();
        tombolGantibk = new javax.swing.JButton();
        tombolHapusbk = new javax.swing.JButton();
        idbarangbk = new javax.swing.JTextField();
        textJumlahbk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelbk = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idbarangk = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_regis = new javax.swing.JButton();
        btn_datab = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tombolSimpanbk.setText("Simpan");
        tombolSimpanbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolSimpanbkActionPerformed(evt);
            }
        });

        tombolGantibk.setText("Ganti");
        tombolGantibk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolGantibkActionPerformed(evt);
            }
        });

        tombolHapusbk.setText("Hapus");
        tombolHapusbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHapusbkActionPerformed(evt);
            }
        });

        idbarangbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idbarangbkActionPerformed(evt);
            }
        });

        jLabel4.setText("Id Barang");

        tabelbk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelbk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelbkMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelbk);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("INPUT DATA BARANG KELUAR");

        jLabel5.setText("Jumlah Barang");

        jLabel7.setText("tanggal keluar");

        idbarangk.setEnabled(false);
        idbarangk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idbarangkActionPerformed(evt);
            }
        });

        jLabel8.setText("Id Barang Keluar");

        btn_regis.setText("registrasi >");
        btn_regis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regisActionPerformed(evt);
            }
        });

        btn_datab.setText("< Input data barang");
        btn_datab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_databActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(textJumlahbk, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addComponent(idbarangbk, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tanggalkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tombolSimpanbk)
                                .addGap(119, 119, 119)
                                .addComponent(tombolGantibk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tombolHapusbk))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(idbarangk, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_datab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_regis)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idbarangk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idbarangbk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textJumlahbk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(tanggalkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolSimpanbk)
                    .addComponent(tombolGantibk)
                    .addComponent(tombolHapusbk))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_datab)
                    .addComponent(btn_regis))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolHapusbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHapusbkActionPerformed
        // TODO add your handling code here:
        try {
            this.stat=k.getKoneksi().prepareStatement("delete from barang_keluar where id_barang_keluar=?");       
            stat.setInt(1, Integer.parseInt(idbarangk.getText()));
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_tombolHapusbkActionPerformed

    private void idbarangkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idbarangkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idbarangkActionPerformed

    private void btn_regisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regisActionPerformed
        // TODO add your handling code here:
        registrasi reg=new registrasi();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_regisActionPerformed

    private void btn_databActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_databActionPerformed
        // TODO add your handling code here:
        tambahdatabarang reg=new tambahdatabarang();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_databActionPerformed

    private void idbarangbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idbarangbkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idbarangbkActionPerformed

    private void tombolSimpanbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolSimpanbkActionPerformed
        // TODO add your handling code here:
        try {
            tambahbarangk b=new tambahbarangk();
            this.stat=k.getKoneksi().prepareStatement("insert into barang_keluar values (?,?,?,?)");
            stat.setInt(1, 0);
            stat.setInt(2, b.id_barang);
            stat.setInt(3, b.jumlah);
            stat.setString(4, b.tanggal_keluar);
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_tombolSimpanbkActionPerformed

    private void tabelbkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelbkMouseClicked
        // TODO add your handling code here:
        idbarangk.setText(model.getValueAt(tabelbk.getSelectedRow(), 0).toString());
        idbarangbk.setText(model.getValueAt(tabelbk.getSelectedRow(), 1).toString());
        textJumlahbk.setText(model.getValueAt(tabelbk.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_tabelbkMouseClicked

    private void tombolGantibkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolGantibkActionPerformed
        // TODO add your handling code here:
         try {
            tambahbarangk b=new tambahbarangk();
            b.id_barang_keluar=Integer.parseInt(idbarangk.getText());
            this.stat=k.getKoneksi().prepareStatement("update barang_keluar set id_barang=?,"
                    + "jumlah=?,tanggal_keluar=? where id_barang_keluar=?");            
            stat.setInt(1, b.id_barang);
            stat.setInt(2, b.jumlah);
            stat.setString(3,b.tanggal_keluar);
            stat.setInt(4, b.id_barang_keluar);
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_tombolGantibkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahdatabarangk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahdatabarangk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahdatabarangk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahdatabarangk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahdatabarangk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_datab;
    private javax.swing.JButton btn_regis;
    private javax.swing.JTextField idbarangbk;
    private javax.swing.JTextField idbarangk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelbk;
    private com.toedter.calendar.JDateChooser tanggalkeluar;
    private javax.swing.JTextField textJumlahbk;
    private javax.swing.JButton tombolGantibk;
    private javax.swing.JButton tombolHapusbk;
    private javax.swing.JButton tombolSimpanbk;
    // End of variables declaration//GEN-END:variables
}
