/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gudang;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author redmibook
 */
public class tambahdatabarang extends javax.swing.JFrame {
    private DefaultTableModel model=null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k=new koneksi();

    /**
     * Creates new form tambahdatabarang
     */
    public tambahdatabarang() {
        initComponents();
        k.connect();
        refreshTable();
    }
    
    class tambahbarang extends tambahdatabarang{
        int id_barang,stok;
        String nama_barang,jenis_barang,kode_barang;
        
        public tambahbarang() {
            this.nama_barang = textNamabarang.getText();
            this.jenis_barang = textJenisbarang.getText();
            this.kode_barang = textkodebarang.getText();
        }
    }
    
        
        public void refreshTable(){
            model= new DefaultTableModel();
            model.addColumn("ID Barang");
            model.addColumn("Nama Barang");
            model.addColumn("Jenis Barang");
            model.addColumn("Kode Barang");
            model.addColumn("Stok");
            tabelbarang.setModel(model);
            try {
                this.stat=k.getKoneksi().prepareStatement("select * from barang");
                this.rs=this.stat.executeQuery();
                while(rs.next()){
                    Object[] data={
                        rs.getInt("id_barang"),
                        rs.getString("nama_barang"),
                        rs.getString("jenis_barang"),
                        rs.getString("kode_barang"),
                        rs.getInt("stok")
                    };
                    model.addRow(data);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
            textNamabarang.setText("");
            textJenisbarang.setText("");
            textkodebarang.setText("");      
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textNamabarang = new javax.swing.JTextField();
        textJenisbarang = new javax.swing.JTextField();
        textkodebarang = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelbarang = new javax.swing.JTable();
        tombolsimpanbarang = new javax.swing.JButton();
        tombolgantibarang = new javax.swing.JButton();
        tombolhapusbarang = new javax.swing.JButton();
        btn_databm = new javax.swing.JButton();
        btn_databk = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        idbarang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("INPUT DATA BARANG");

        jLabel3.setText("Nama Barang");

        jLabel4.setText("Jenis Barang");

        jLabel5.setText("Kode Barang");

        textNamabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNamabarangActionPerformed(evt);
            }
        });

        tabelbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelbarangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelbarang);

        tombolsimpanbarang.setText("Simpan");
        tombolsimpanbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolsimpanbarangActionPerformed(evt);
            }
        });

        tombolgantibarang.setText("Ganti");
        tombolgantibarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolgantibarangActionPerformed(evt);
            }
        });

        tombolhapusbarang.setText("Hapus");
        tombolhapusbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolhapusbarangActionPerformed(evt);
            }
        });

        btn_databm.setText("< Input data masuk");
        btn_databm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_databmActionPerformed(evt);
            }
        });

        btn_databk.setText("Input data keluar >");
        btn_databk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_databkActionPerformed(evt);
            }
        });

        btn_logout.setText("LOG OUT");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        idbarang.setEnabled(false);
        idbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idbarangActionPerformed(evt);
            }
        });

        jLabel6.setText("Id Barang");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_logout))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn_databk)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tombolsimpanbarang)
                                .addGap(122, 122, 122)
                                .addComponent(tombolgantibarang)
                                .addGap(124, 124, 124)
                                .addComponent(tombolhapusbarang))
                            .addComponent(btn_databm))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textkodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(textJenisbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)
                                            .addComponent(textNamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(idbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btn_logout))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textJenisbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textkodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolsimpanbarang)
                    .addComponent(tombolgantibarang)
                    .addComponent(tombolhapusbarang))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_databm)
                    .addComponent(btn_databk))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolhapusbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolhapusbarangActionPerformed
        // TODO add your handling code here:
        try {
            this.stat=k.getKoneksi().prepareStatement("delete from barang where id_barang=?");       
            stat.setInt(1, Integer.parseInt(idbarang.getText()));
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_tombolhapusbarangActionPerformed

    private void textNamabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNamabarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNamabarangActionPerformed

    private void tombolgantibarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolgantibarangActionPerformed
        // TODO add your handling code here:
        try {
            tambahbarang b=new tambahbarang();
            this.stat=k.getKoneksi().prepareStatement("update barang set nama_barang=?,"
                    + "jenis_barang=?,kode_barang=?,stok=? where id_barang=?");
            
            stat.setString(1, b.nama_barang);
            stat.setString(2, b.jenis_barang);
            stat.setString(3,b.kode_barang);
            stat.setInt(4, b.stok);
            stat.setInt(5, Integer.parseInt(idbarang.getText()));
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_tombolgantibarangActionPerformed

    private void tombolsimpanbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolsimpanbarangActionPerformed
        // TODO add your handling code here:
        try {
            tambahbarang b=new tambahbarang();
            this.stat=k.getKoneksi().prepareStatement("insert into barang values (?,?,?,?,?)");
            stat.setInt(1, b.id_barang);
            stat.setString(2, b.nama_barang);
            stat.setString(3, b.jenis_barang);
            stat.setString(4,b.kode_barang);
            stat.setInt(5, b.stok);
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_tombolsimpanbarangActionPerformed

    private void tabelbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelbarangMouseClicked
        // TODO add your handling code here:
        idbarang.setText(model.getValueAt(tabelbarang.getSelectedRow(), 0).toString());
        textNamabarang.setText(model.getValueAt(tabelbarang.getSelectedRow(), 1).toString());
        textJenisbarang.setText(model.getValueAt(tabelbarang.getSelectedRow(), 2).toString());
        textkodebarang.setText(model.getValueAt(tabelbarang.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_tabelbarangMouseClicked

    private void btn_databkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_databkActionPerformed
        // TODO add your handling code here:
        tambahdatabarangk reg=new tambahdatabarangk();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_databkActionPerformed

    private void btn_databmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_databmActionPerformed
        // TODO add your handling code here:
        tambahdatabarangm reg=new tambahdatabarangm();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_databmActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        login l = new login();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void idbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idbarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahdatabarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahdatabarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahdatabarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahdatabarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahdatabarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_databk;
    private javax.swing.JButton btn_databm;
    private javax.swing.JButton btn_logout;
    private javax.swing.JTextField idbarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelbarang;
    private javax.swing.JTextField textJenisbarang;
    private javax.swing.JTextField textNamabarang;
    private javax.swing.JTextField textkodebarang;
    private javax.swing.JButton tombolgantibarang;
    private javax.swing.JButton tombolhapusbarang;
    private javax.swing.JButton tombolsimpanbarang;
    // End of variables declaration//GEN-END:variables
}
